import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { Header } from '@/components/layout/Header';
import { Sidebar } from '@/components/layout/Sidebar';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-future",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} antialiased bg-slate-950 text-slate-100`}>
        <Header />
        <div className="flex">
          <Sidebar />
          <main className="flex-1 min-h-screen bg-[radial-gradient(1200px_circle_at_20%_-10%,rgba(34,211,238,0.08),transparent_45%),radial-gradient(900px_circle_at_80%_-20%,rgba(59,130,246,0.08),transparent_40%),linear-gradient(180deg,#0b0f14,#0b0f14)]" style={{ color: 'var(--foreground)' }}>
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
